### PR TITLE
Fixed issue

### PR DESCRIPTION
**Pull request by mademoiselle-chantal**
### Description

I created a new component called CardComponent.jsx and l added some code to create a card component. I went on and imported and rendered my CardComponent into the App.jsx file.

### Additional Context

This is what l got:

Screen Shot 2023-10-14 at 15 15 51

### CODE REVIEW

**Review by nikohoffren — APPROVED** [review]
Nice, card looks good!

**Comment by nikohoffren** [comment]
## Merged

> This is an automated message from Fork, Commit, Merge [BOT].

Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

### What's next?

If you're looking for more ways to contribute, I invite you to check out my other projects. Just click [here](https://github.com/nikohoffren?tab=repositories) to find more. These projects contain real issues that you can help resolve. You can also check out the [Influences](https://github.com/nikohoffren/fork-commit-merge#influences) section in the README to find more projects similar to this one.

Also please leave a star to this project if you feel it helped you, i would really appreciate it.

I look forward to seeing your contributions!

**Comment by mademoiselle-chantal** [comment]
> Nice, card looks good!

Thanks much @nikohoffren!

**Comment by mademoiselle-chantal** [comment]
> ## Merged
> > This is an automated message from Fork, Commit, Merge [BOT].
> 
> Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.
> 
> ### What's next?
> If you're looking for more ways to contribute, I invite you to check out my other projects. Just click [here](https://github.com/nikohoffren?tab=repositories) to find more. These projects contain real issues that you can help resolve. You can also check out the [Influences](https://github.com/nikohoffren/fork-commit-merge#influences) section in the README to find more projects similar to this one.
> 
> Also please leave a star to this project if you feel it helped you, i would really appreciate it.
> 
> I look forward to seeing your contributions!

And l look forward to contributing even more too. Thanks again, @nikohoffren

**Pull request merged**
