### PR TITLE
Added 3D rotating card effect

### PR DESCRIPTION
**Pull request by ATREAY**
CSS Enhancement for Issue #307 (Fork, Commit, Merge - Hard Issue)

### CODE REVIEW

**Review by nikohoffren — APPROVED** [review]

**Comment by nikohoffren** [comment]
> CSS Enhancement for Issue #307 (Fork, Commit, Merge - Hard Issue)

Looks good!

**Comment by nikohoffren** [comment]
## Merged

> This is an automated message from Fork, Commit, Merge [BOT].

Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

### What's next?

If you're looking for more ways to contribute, I invite you to check out my other projects. Just click [here](https://github.com/nikohoffren?tab=repositories) to find more. These projects contain real issues that you can help resolve. You can also check out the Influences section in the README to find more projects similar to this one.

Also please leave a star to this project if you feel it helped you, i would really appreciate it.

I look forward to seeing your contributions!

**Comment by ATREAY** [comment]
Thank you @nikohoffren for merging the pull request!🙌

**Comment by nikohoffren** [comment]
> Thank you @nikohoffren for merging the pull request!🙌

Thanks for contributing!

**Pull request merged**
