### PR TITLE
Update number_list.py

### PR DESCRIPTION
**Pull request by usmangdeveloper**
updated number_list.py

### CODE REVIEW

**Review by nikohoffren — APPROVED** [review]
Looks good, well done!

**Comment by nikohoffren** [comment]
## Merged

> This is an automated message from Fork, Commit, Merge [BOT].

Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

### What's next?

If you're looking for more ways to contribute, I invite you to check out my other projects. Just click [here](https://github.com/nikohoffren?tab=repositories) to find more. These projects contain real issues that you can help resolve. You can also check out the Influences section in the README to find more projects similar to this one. 

Also please leave a star to this project if you feel it helped you, i would really appreciate it.

I look forward to seeing your contributions!

**Comment by usmangdeveloper** [comment]
Thank you @nikohoffren . Loved your repo. I m not a developer but started using GitHub to learn what this amazing website is and how can I be part of software community with over 100Million developers on it. I was quite taken aback when I discovered this.

**Comment by nikohoffren** [comment]
> Thank you @nikohoffren . Loved your repo. I m not a developer but started using GitHub to learn what this amazing website is and how can I be part of software community with over 100Million developers on it. I was quite taken aback when I discovered this.

Glad to hear that, thanks for contributing. Yeah this website is pretty amazing. Even if you're not a developer i hope to see more of your contributions in all over Github in the future!

**Comment by usmangdeveloper** [comment]
@nikohoffren 
Perfect. Thank you.

**Pull request merged**
