### PR TITLE
Fixed issue

### PR DESCRIPTION
**Pull request by swaroop-2021**
### Description

Creation of a new server using express..js

### Additional Context

- app.js

image

- server

image

### CODE REVIEW

**Review by nikohoffren — APPROVED** [review]
Looks good!

**Comment by swaroop-2021** [comment]
- Closes #621
- Please add Hacktoberfest tags.

**Comment by nikohoffren** [comment]
## Merged

> This is an automated message from Fork, Commit, Merge [BOT].

Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

### What's next?

If you're looking for more ways to contribute, I invite you to check out my other projects. Just click [here](https://github.com/nikohoffren?tab=repositories) to find more. These projects contain real issues that you can help resolve. You can also check out the [Influences](https://github.com/nikohoffren/fork-commit-merge#influences) section in the README to find more projects similar to this one.

Also please leave a star to this project if you feel it helped you, i would really appreciate it.

I look forward to seeing your contributions!

**Comment by nikohoffren** [comment]
> - Closes #621
> - Please add Hacktoberfest tags.

Sorry, but according to Hacktoberfest organizers, this repository is an educational repository, hence against the hacktoberfest guidelines, so this repo is not eligible for Hacktoberfest 2023.

**Pull request merged**
