### PR TITLE
Fixed issue

### LINKED ISSUE #172: Fork, Commit, Merge - Easy Issue (NextJS)
# Fork, Commit, Merge - Easy Issue (NextJS)

## Create a sample product list with names and prices
*Note: You don't have ask permission to start solving the issue or get assigned, since these issues are supposed to be always open for new contributors. The actions-user bot will reset the file back to previous state for the next contributor after your commit is merged. So you can just simply start working with the issue right away!*

Description:
-   Your task  is to create at least three sample products inside of the `sampleProducts` array with names and prices for landing page of an imaginary online store. The landing page displays a welcome message, a brief description of the store, and the sample products.

Start by navigating inside of the directory used in this project with the command:
```bash
cd tasks/nextjs/easy/nextjs-easy` 
```
Then run `npm i` to install NextJS, React and all the necessary dependencies for the project.

After installing the dependencies you can open the `index.tsx` file inside of `src/pages` directory, and start implementing your solution!

---

This project uses Tailwind for CSS and all the classes are already added to the components.
This project also uses TypeScript but you don't need to know any TypeScript to work with this issue. As soon as you add the sample products with names and prices, TypeScript will infer the types and all the errors present in the file will go away.

After you are done with the list, make sure you are in the `tasks/react/easy/next-easy` in your terminal and run `npm run dev` to start the NextJS server. Then, open "http://localhost:3000/" in your browser to check how the landing page looks.

If the product names and prices are showing up as they should, you are ready to make a pull request!

---

To work with this issue, you need to have npm and NodeJS installed to your local machine.
Check out [README.md](https://github.com/nikohoffren/fork-commit-merge/blob/main/README.md) for more instructions of installing npm and NodeJS as well as how to make a pull request.

---

Feel free to ask any questions here if you have some problems!

#### Also, kindly give this project a star to enhance its visibility for new developers!

### PR DESCRIPTION
**Pull request by ayushsgithub**
Fixes #172 
Added sample products.

### CODE REVIEW

**Comment by ayushsgithub** [comment]
Hey, I just contributed to the code and pushed it but why the bot says this PR has 0 quantified lines of changes

**Review by nikohoffren — APPROVED** [review]
Looks good!

**Comment by nikohoffren** [comment]
## Merged

> This is an automated message from Fork, Commit, Merge [BOT].

Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

### What's next?

If you're looking for more ways to contribute, I invite you to check out my other projects. Just click [here](https://github.com/nikohoffren?tab=repositories) to find more. These projects contain real issues that you can help resolve. You can also check out the Influences section in the README to find more projects similar to this one. 

Also please leave a star to this project if you feel it helped you, i would really appreciate it.

I look forward to seeing your contributions!

**Comment by ayushsgithub** [comment]
> Looks good!

Thank You

**Pull request merged**
