### PR TITLE
Update sum.js

### PR DESCRIPTION
**Pull request by nshnt777**

### CODE REVIEW

**Review by nikohoffren — APPROVED** [review]
Looks good! You can also write that very shortly with arrow function:
```bash
const sum = (a, b) => a + b;
const a = 1;
const b = 2;
const result = sum(a, b);
console.log("The sum of " + a + " and " + b + " is " + result + ".");
```

**Comment by nikohoffren** [comment]
## Merged

> This is an automated message from Fork, Commit, Merge [BOT].

Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

### What's next?

If you're looking for more ways to contribute, I invite you to check out my other projects. Just click [here](https://github.com/nikohoffren?tab=repositories) to find more. These projects contain real issues that you can help resolve. You can also check out the [Influences](https://github.com/nikohoffren/fork-commit-merge#influences) section in the README to find more projects similar to this one.

Also please leave a star to this project if you feel it helped you, i would really appreciate it.

I look forward to seeing your contributions!

**Comment by nshnt777** [comment]
Yeah, right. Just starting out on open source and GitHub. I don't really have a lot of clue on collaborating with others and maintaining readability. Thanks for the tip! You're doing a great work for beginners like me. I'll be spending some more time with your repo to get familiar with open source contributions.

**Comment by nikohoffren** [comment]
> Yeah, right. Just starting out on open source and GitHub. I don't really have a lot of clue on collaborating with others and maintaining readability. Thanks for the tip! You're doing a great work for beginners like me. I'll be spending some more time with your repo to get familiar with open source contributions.

Thank you! Im glad if this repo can help developers with contributing to open source. You can also find some really useful resources on our [website](https://forkcommitmerge.io).

**Pull request merged**
