### PR TITLE
Flask config setup --staged

### PR DESCRIPTION
**Pull request by Abhishek-Mallick**
## Pull Request Type

What kind of change does this PR introduce?

- [x] Solved an issue/task
- [x] Feature

## What is the current behavior?
Added `Flask` template for `tasks/flask/medium`

Issue Number: https://github.com/nikohoffren/fork-commit-merge/issues/1050

## What is the new behavior?

Added medium `Flask` web app along with `templates`

#hacksquad

### CODE REVIEW

**Review by nikohoffren — CHANGES_REQUESTED** [review]
Hi!

Do you want to add this project as a new task for new contributors to solve?
If so, there would be some parts needed to be removed and instead TODO comments added about what the contributors would need to add to get the app working.
This repository only has tasks that need to be solved.

**Comment by Abhishek-Mallick** [comment]
Hey @nikohoffren ,
I am looking to add this project under `tasks/flask/medium` It would offer as a base template for people looking for how to synchronize flask's `app.py` with `templates` and to have a understanding how to render and route different pages through `app.py`

**Comment by nikohoffren** [comment]
> Hey @nikohoffren ,
> I am looking to add this project under `tasks/flask/medium` It would offer as a base template for people looking for how to synchronize flask's `app.py` with `templates` and to have a understanding how to render and route different pages through `app.py`

This repository has only tasks that contributors can solve, we don't really add any example code here. Most of the tasks are as simple as possible, since this repository is mostly for beginners or people who are new in open source in general. You can create a new task if you like or try to solve some of our 120 different tasks that we have so far.

**Comment by nikohoffren** [comment]
Do you want to create a task from this? There would be some parts needed to be removed and instead TODO comments added about what the contributors would need to add to get the app working.
This repository only has tasks that need to be solved.

If not, i'll close this pull request.

**Comment by nikohoffren** [comment]
Closed with no response from contributor.

**Pull request closed without merging**
