### PR TITLE
clock

### PR DESCRIPTION
**Pull request by krishvsoni**
### Description

I had added my live clock project in your repository 
### Additional Context
It is good to show case the live clock project which inspires users to build something.

image

### CODE REVIEW

**Review by nikohoffren — CHANGES_REQUESTED** [review]
Hi!

That's a nice clock project but this repository has only issues where contributors have to solve some kind of problems in different languages/frameworks.

I think this clock project could be added as a new task to this project if you could remove some parts from all of the files and write some TODO comments about what the contributors would have to do to make a the clock work. I can then later on write an actual issue for it. You would also get your profile name to the issue description as the creator of this task. 

Feel free to ask if you have some questions!

**Comment by krishvsoni** [comment]
> Hi!
> 
> That's a nice clock project but this repository has only issues where contributors have to solve some kind of problems in different languages/frameworks.
> 
> I think this clock project could be added as a new task to this project if you could remove some parts from all of the files and write some TODO comments about what the contributors would have to do to make a the clock work. I can then later on write an actual issue for it. You would also get your profile name to the issue description as the creator of this task.
> 
> Feel free to ask if you have some questions!

Like in TODO comments what I have to write and what part of the files should be removed ?

**Comment by nikohoffren** [comment]
> > Hi!
> > That's a nice clock project but this repository has only issues where contributors have to solve some kind of problems in different languages/frameworks.
> > I think this clock project could be added as a new task to this project if you could remove some parts from all of the files and write some TODO comments about what the contributors would have to do to make a the clock work. I can then later on write an actual issue for it. You would also get your profile name to the issue description as the creator of this task.
> > Feel free to ask if you have some questions!
> 
> Like in TODO comments what I have to write and what part of the files should be removed ? Do I have to raise an issue?

No, you don't need to raise an issue. I can later on create the issue myself for new contributors to solve.
You can remove some parts from for example the JavaScript file and add the TODO comments like this:
```javascript
setInterval(setClock, 1000)

const hourHand = document.querySelector('[data-hour-hand]')
const minuteHand = document.querySelector('[data-minute-hand]')
const secondHand = document.querySelector('[data-second-hand]')

function setClock() {
  // TODO: Implement the setClock function
}

// TODO: Create setRotation function

setClock();
```

And also maybe remove some parts from the html and css file and add comments to them of what the contributors would need to do. It is really up to you how many parts you want to remove, depends how difficult you want this task to be.

You can just make the modifications and push a new commit to this same kvs-b1 branch so it updates straight to this pull request.

**Comment by krishvsoni** [comment]
> > > Hi!
> > > That's a nice clock project but this repository has only issues where contributors have to solve some kind of problems in different languages/frameworks.
> > > I think this clock project could be added as a new task to this project if you could remove some parts from all of the files and write some TODO comments about what the contributors would have to do to make a the clock work. I can then later on write an actual issue for it. You would also get your profile name to the issue description as the creator of this task.
> > > Feel free to ask if you have some questions!
> > 
> > 
> > Like in TODO comments what I have to write and what part of the files should be removed ? Do I have to raise an issue?
> 
> No, you don't need to raise an issue. I can later on create the issue myself for new contributors to solve. You can remove some parts from for example the JavaScript file and add the TODO comments like this:
> 
> ```js
> setInterval(setClock, 1000)
> 
> const hourHand = document.querySelector('[data-hour-hand]')
> const minuteHand = document.querySelector('[data-minute-hand]')
> const secondHand = document.querySelector('[data-second-hand]')
> 
> function setClock() {
>   // TODO: Implement the setClock function
> }
> 
> // TODO: Create setRotation function
> 
> setClock();
> ```
> 
> And also maybe remove some parts from the html and css file and add comments to them of what the contributors would need to do. It is really up to you how many parts you want to remove, depends how difficult you want this task to be.
> 
> You can just make the modifications and push a new commit to this same kvs-b1 branch so it updates straight to this pull request.

YEAH I am removing the comments

**Comment by krishvsoni** [comment]
Do we need TODO comments in html and css? I had updated in my js code.

**Comment by nikohoffren** [comment]
> Do we need TODO comments in html and css? I had updated in my js code.

You can also remove some parts of the html and css files and add TODO comments instead. 
And you would need also to remove the parts where you added the comments so the contributors have to actually write the code themselves. Similarly like here:
```javascript
// Implement the setClock function to update the positions of the hour, minute, and second hands on the clock based on the current time.

setInterval(setClock, 1000)

const hourHand = document.querySelector('[data-hour-hand]')
const minuteHand = document.querySelector('[data-minute-hand]')
const secondHand = document.querySelector('[data-second-hand]')

function setClock() {
  const currentDate = new Date()

  // Calculate the rotation ratios for the hour, minute, and second hands.

  // Set the rotation of the hour, minute, and second hands.
}

// Create setRotation function to rotate a DOM element around its center point. This function will be used to rotate the hour, minute, and second hands on the clock.

setClock();
```

**Comment by krishvsoni** [comment]
We can do one thing I give the clean code and on header i give the comments, is it ok?

**Comment by nikohoffren** [comment]
> We can do one thing I give the clean code and on header i give the comments, is it ok?

These tasks should follow the same principle as all the other tasks in this repository, so there should be some parts removed and TODO comments added instead, so there is something to solve for the contributors. That's what this repo is all about. So the files would need to look similar as the code snippet i presented earlier.

If you don't want anything removed from the code that's fine too, but then this cannot be added since there is not anything to solve.

**Comment by krishvsoni** [comment]
No problem I remove some part of code and tell the contributors to write full.
Give me time to remove the parts. And one more thing in which file I remove the code , in js only or in html and css also ?

**Comment by nikohoffren** [comment]
> No problem I remove some part of code and tell the contributors to write full. Give me time to remove the parts. And one more thing in which file I remove the code , in js only or in html and css also ?

Sounds good! You can remove some parts from html and css files too, like for example some of the css classes:
```css
body {
  TODO: Add styles to the body class
}

.clock {
  TODO: Add styles to the clock class
}
```

**Comment by krishvsoni** [comment]
Done with the task now you can ask contributors to write the code. I have made changes in html and js.

**Comment by krishvsoni** [comment]
In the CSS code above, I've added comments indicating where contributors need to make changes or add styles. They should focus on completing the TODOs.

**Comment by nikohoffren** [comment]
## Merged

> This is an automated message from Fork, Commit, Merge [BOT].

Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

### What's next?

If you're looking for more ways to contribute, I invite you to check out my other projects. Just click [here](https://github.com/nikohoffren?tab=repositories) to find more. These projects contain real issues that you can help resolve. You can also check out the [Influences](https://github.com/nikohoffren/fork-commit-merge#influences) section in the README to find more projects similar to this one.

Also please leave a star to this project if you feel it helped you, i would really appreciate it.

I look forward to seeing your contributions!

**Comment by krishvsoni** [comment]
> Looks good! I will create issue from this later for new contributors to solve.

Thanks alot 😊

**Pull request merged**
