### PR TITLE
Fixed issue

### PR DESCRIPTION
**Pull request by rasel9t6**
## Pull Request Type

What kind of change does this PR introduce?

[x] Solved an issue/task
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:

## What is the current behavior?

No products array, shop name not relevant, styles ar not good.
Issue Number: [ #1372 ]

## What is the new behavior?

Added product array, change shop name, changes some tailwind css style.
## Other information

**Before:**
Screenshot 2023-11-02 111029

**After:**
Screenshot 2023-11-02 110810

### CODE REVIEW

**Review by nikohoffren — APPROVED** [review]
Looks good! That's a professional looking product sample page.

**Comment by nikohoffren** [comment]
## Merged

> This is an automated message from Fork, Commit, Merge [BOT].

Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

### What's next?

If you're looking for more ways to contribute, I invite you to check out my other projects. Just click [here](https://github.com/nikohoffren?tab=repositories) to find more. These projects contain real issues that you can help resolve. You can also check out the [Influences](https://github.com/nikohoffren/fork-commit-merge#influences) section in the README to find more projects similar to this one.

Also please leave a star to this project if you feel it helped you, i would really appreciate it.

I look forward to seeing your contributions!

**Comment by rasel9t6** [comment]
‍This was my first open source contribution. I am very happy to have done everything right. Hopefully this inspiration will help me go a long way. Thank you very much for your valuable feedback.

**Comment by nikohoffren** [comment]
> ‍This was my first open source contribution. I am very happy to have done everything right. Hopefully this inspiration will help me go a long way. Thank you very much for your valuable feedback.

Thanks, no problem! Hopefully this repository helped you out in your open source journey.

**Pull request merged**
