### PR TITLE
Flask hard

### PR DESCRIPTION
**Pull request by Abhishek-Mallick**
## Pull Request Type

What kind of change does this PR introduce?

- [x] Solved an issue/task
- [x] Feature

## What is the current behavior?
Added blog-app to `flask-hard` with `db` configuration

Issue Number: https://github.com/nikohoffren/fork-commit-merge/issues/1050

#hacksquad

### CODE REVIEW

**Comment by Abhishek-Mallick** [comment]
This PR contains all the code for a blog-app made using `Flask`

**Comment by nikohoffren** [comment]
> This PR contains all the code for a `blog-app` made using `Flask`

This repository has only tasks that contributors can solve, we don't really add any example code here. Most of the tasks are as simple as possible, since this repository is mostly for beginners or people who are new in open source in general. You can create a new task if you like or try to solve some of our 120 different tasks that we have so far.

**Review by nikohoffren — CHANGES_REQUESTED** [review]
As i said in previous PR, we don't add any example code here. This can be updated as a task for this repo but it is way too big, it has currently 330 000 lines of code. Considering that most of the tasks in this repo has only couple lines of code, this would bloat the whole repository.

**Comment by nikohoffren** [comment]
Closed for extra large size and dependency review failing.

**Pull request closed without merging**
