### PR TITLE
fix: fixed landing-page

### LINKED ISSUE #257: Fork, Commit, Merge - Medium Issue (Bootstrap CSS)
# Fork, Commit, Merge - Medium Issue (Bootstrap CSS)

## Implement a Responsive Product Landing Page using Bootstrap
*Note: You don't have ask permission to start solving the issue or get assigned, since these issues are supposed to be always open for new contributors. The actions-user bot will reset the file back to previous state for the next contributor after your commit is merged. So you can just simply start working with the issue right away!*

Navigate to the `tasks/bootstrap/medium` directory from the root of the project.
Then open the `landing-page.html` file to start working with the solution.

---

### Description:

The goal of this issue is to create a responsive product landing page using the Bootstrap framework.
You need to add all the missing classes to make the page look similar as in all the screenshots. Some classes are already added, you don't need to modify those. Also, you don't need to modify any of the HTML or example text provided in the page.

### Screenshots:

bootstrap-medium-screenshot
bootstrap-medium-screenshot2
bootstrap-medium-screenshot-mobile
bootstrap-medium-screenshot-mobile2
bootstrap-medium-screenshot-mobile3

### Requirements:

-   Must utilize Bootstrap's Grid system for layout
-   Must be fully responsive and look good on all devices (mobile, tablet, desktop)
-   In mobile view, the Navbar should open up, when clicking the hamburger-icon
-   Use Bootstrap components like Navbar, Buttons, Cards, Forms, etc.
-   Stick to the Bootstrap color scheme or choose a harmonious palette

### Bonus:

-   Add smooth scrolling to the page
-   Include animations or transitions for a polished look

### Resources:

[Bootstrap Documentation](https://getbootstrap.com/docs/5.0/getting-started/introduction/)

---

If you are using VS Code and have for example Live Server extension, you can simply open `landing-page.html` with the server and check how the card looks. After the card is done, you are ready to make a pull request!
If you do not have Live Server extension, you'll find information about installing and how to use it [here](https://www.donskytech.com/visual-studio-code-live-server/).

Check out [README.md](https://github.com/nikohoffren/fork-commit-merge/blob/main/README.md) for more instructions and how to make a pull request.

Feel free to ask any questions here if you have some problems!

#### Also, kindly give this project a star to enhance its visibility for new developers!

### PR DESCRIPTION
**Pull request by rameshvoodi**
## fixed landing page

fixes #257

-added responsiveness to page

##Video

https://github.com/nikohoffren/fork-commit-merge/assets/53528683/5340ec6d-579d-4241-98d0-18525f8a9745

### CODE REVIEW

**Comment by rameshvoodi** [comment]
Mr @nikohoffren iam new to open source, should i include these changes to next issue or should i change only issue file. thank you.

**Comment by nikohoffren** [comment]
> Mr @nikohoffren iam new to open source, should i include these changes to next issue or should i change only issue file. thank you.

Hi! You can make a new branch for each issue, there is no need to add the previous changes.

**Comment by nikohoffren** [comment]
> ## fixed landing page
> 
> fixes #257
> 
> -added responsiveness to page
> 
> ##Video
> Product.Landing.Page.mp4

Page looks really good with proper classes, well done!

**Comment by rameshvoodi** [comment]
> > Mr @nikohoffren iam new to open source, should i include these changes to next issue or should i change only issue file. thank you.
> 
> Hi! You can make a new branch for each issue, there is no need to add the previous changes
Oh thank you.

**Pull request merged**
