### PR TITLE
fix-issue-6

### PR DESCRIPTION
**Pull request by Egnodia**
## Pull Request Type

What kind of change does this PR introduce?

[x] Solved an issue/task
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:

## What is the current behavior?
Created a Card using CSS styling.

Issue Number: #1271

### CODE REVIEW

**Review by nikohoffren — CHANGES_REQUESTED** [review]
Code looks good! However, looks like there are some conflicts that you have to resolve in your file, not sure if the issue is that you have older clone of the repository or what.

**Comment by Egnodia** [comment]
How do I check if I have a older repository ?

**Comment by nikohoffren** [comment]
> How do I check if I have a older repository ?

I don't if that is the issue but you can first just click the 'resolve conflicts' button in this page and see what the conflicts are. You can then share for example a screenshot of what is the issue. It is probably just a very minor thing in the file.

**Comment by Egnodia** [comment]
They say its too complexed to resolve conflicts here but everything seems fine when I go into the styles.css file

**Comment by nikohoffren** [comment]
> They say its too complexed to resolve conflicts here but everything seems fine when I go into the styles.css file

Okay, i think there are some conflicts because you probably have that older repository. I make changes to this repo every day so once in a while contributors will have to pull the latest changes to their own cloned repository, otherwise some of the files may be different in the actual repo and your own cloned repo.

You can do that in the [Setup Instructions](https://github.com/nikohoffren/fork-commit-merge#setup-instructions). You can open your cloned repository in the code editor just like you would normally, and then do everything after the `4. Add a reference to the original repository for future updates` part.

After doing all of that you can make a new branch and do the task again and make a new pull request. I'm going to close this one.

**Comment by Egnodia** [comment]
should I do this on the main branch or the fix-issue branch ?

**Comment by nikohoffren** [comment]
> should I do this on the main branch or the fix-issue branch ?

You can do it on the main branch and when you start working with the issues you can create new branch to commit to.

**Comment by Egnodia** [comment]
oh great I git pull upstream main into the fix-issue branch how do I undo this ?

**Comment by nikohoffren** [comment]
> oh great I git pull upstream main into the fix-issue branch how do I undo this ?

The simpliest solution is that you delete your repository from your local machine and from your Github account. Then just clone this repository again and you'll get the latest repo.

**Comment by Egnodia** [comment]
ok I did everything you said and now when i'm cloning the repository again I get this :

Screenshot (2)

**Comment by nikohoffren** [comment]
> ok I did everything you said and now when i'm cloning the repository again I get this :
> 
> Screenshot (2)
> 

You have to delete the previous cloned repository from your computer too, it is probably still there.

**Comment by Egnodia** [comment]
Every Thing good here ? : 
Screenshot (3)

**Comment by nikohoffren** [comment]
> Every Thing good here ? : Screenshot (3)

You have to delete the whole fork-commit-merge directory so use `rm -rf ./*` but be extremely sure you are inside of the fork-commit-merge directory as you are in the screenshot, otherwise you can accidently delete some other directories with that command.

**Comment by Egnodia** [comment]
Ok how do I look now ?

**Comment by Egnodia** [comment]
How do I look now ?
Screenshot (4)

**Comment by nikohoffren** [comment]
> How do I look now ?
> Screenshot (4)
> 

If the fork-commit-merge directory is not there, you can clone the new repository. You can check by going back one with 'cd ..' and doing 'ls' again or just check with your file explorer.

**Comment by Egnodia** [comment]
It's still there

**Comment by nikohoffren** [comment]
> It's still there 

You have to delete the folder, so since you are on Windows, easier is to just delete it with the normal file explorer. Or you can go in the directory where the fork-commit-merge folder is and do 'rm -rf fork-commit-merge'.

**Comment by Egnodia** [comment]
Ok finally its not there 👍🏿

**Comment by Egnodia** [comment]
After I redo everything, do I have to start over everything I did ?

**Comment by nikohoffren** [comment]
> After I redo everything, do I have to start over everything I did ? 

You can copypaste the code from this PR to your new repository so you don't have to start again.

**Comment by nikohoffren** [comment]
> Ok finally its not there 👍🏿 

Great!

**Comment by Egnodia** [comment]
> > After I redo everything, do I have to start over everything I did ?
> 
> You can copypaste the code from this PR to your new repository so you don't have to start again.

And how do I do that ?

**Comment by nikohoffren** [comment]
> > > After I redo everything, do I have to start over everything I did ?
> > 
> > You can copypaste the code from this PR to your new repository so you don't have to start again.
> 
> And how do I do that ?

Just click that 'files changed' button on the top of this page and copy your code that you made previously and paste it to the new file on your cloned repository.

**Pull request closed without merging**
