### PR TITLE
Stopwatch using Javascript

### PR DESCRIPTION
**Pull request by imsoumik03**
issue #703 

### Description
I have made a simple javascript countdown timer by changing the the file `./tasks/javascript/medium/script.js`

### CODE REVIEW

**Review by nikohoffren — APPROVED** [review]
Code looks good! Just remember to use 'let' or 'const' when declaring variables since 'var' is considered unsafe and deprecated these days.

**Comment by nikohoffren** [comment]
## Merged

> This is an automated message from Fork, Commit, Merge [BOT].

Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

### What's next?

If you're looking for more ways to contribute, I invite you to check out my other projects. Just click [here](https://github.com/nikohoffren?tab=repositories) to find more. These projects contain real issues that you can help resolve. You can also check out the [Influences](https://github.com/nikohoffren/fork-commit-merge#influences) section in the README to find more projects similar to this one.

Also please leave a star to this project if you feel it helped you, i would really appreciate it.

I look forward to seeing your contributions!

**Comment by Hekt000r** [comment]
The minutes will display incorrectly ()You used "00" + ":" + time which will never show the minutes. Thats just a quick tip since i was working here too

**Comment by imsoumik03** [comment]
@Hekt000r  No need to show minute as it is a stopwatch of 10 seconds.

**Comment by Hekt000r** [comment]
If we had it would though. Hardcoding is not a good idea

**Pull request merged**
