### PR TITLE
Fixed issue of easy HTML task 

### LINKED ISSUE #41: Fork, Commit, Merge - Easy Issue (HTML)
## Fork, Commit, Merge - Easy Issue (HTML)
*Note: You don't have ask permission to start solving the issue or get assigned, since these issues are supposed to be always open for new contributors. The actions-user bot will reset the file back to previous state for the next contributor after your commit is merged. So you can just simply start working with the issue right away!*

Open the `tasks/html/easy` directory from the root of your project.

Your task is to insert an h1 tag with the name `John Doe` above the h2 tag in the `index.html` file.
*Note: Only the `index.html` file needs modification for this task.*

Check out [README.md](https://github.com/nikohoffren/fork-commit-merge/blob/main/README.md) for more instructions and how to make a pull request.

Feel free to ask any questions here if you have some problems!

#### Also, kindly give this project a star to enhance its visibility for new developers!

### PR DESCRIPTION
**Pull request by Layak-Ali**
Added an h1 tag with the name "John Doe" above the h2 tag and completed the task.

### CODE REVIEW

**Review by nikohoffren — APPROVED** [review]

**Comment by nikohoffren** [comment]
> Added an h1 tag with the name "John Doe" above the h2 tag and completed the task.

Looks good!

**Comment by nikohoffren** [comment]
## Merged

> This is an automated message from Fork, Commit, Merge [BOT].

Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

### What's next?

If you're looking for more ways to contribute, I invite you to check out my other projects. Just click [here](https://github.com/nikohoffren?tab=repositories) to find more. These projects contain real issues that you can help resolve.

Also please leave a star to this project if you feel it helped you, i would really appreciate it.

I look forward to seeing your contributions!

**Comment by Layak-Ali** [comment]
Yeah ofcourse Niko.

I've tried contributing to open source since a year but could never successfully change the code and get my pull request merged in other projects. But this project actually made me understand how to contribute. 
I would suggest this to all my friends and juniors in the future.

Thanks.

**Comment by nikohoffren** [comment]
> Yeah ofcourse Niko.
> 
> I've tried contributing to open source since a year but could never successfully change the code and get my pull request merged in other projects. But this project actually made me understand how to contribute. 
> I would suggest this to all my friends and juniors in the future.
> 
> Thanks.

I'm glad to hear this project helps just even a bit! Yeah getting pull requests merged can be tough in the beginning, it was for me too. You can also do just typo checking or find broken links of README files in other projects and make a pull request if you find some, those can be a good way to get some pull requests merged and later on try to tackle some actual code issues.

**Comment by Layak-Ali** [comment]
Thanks for the suggestion.

I will try to contribute to your other projects too.

**Pull request merged**
