### PR TITLE
Create Nearest_Exit.py

### PR DESCRIPTION
**Pull request by nik-6174**
### Description
Added a python file.

This is a solution to the problem of the nearest exit in a Maze.  I have solved it using two different approaches, one using sets and one using DP. I've also attached the link to the problem (LeetCode).

### CODE REVIEW

**Comment by nikohoffren** [comment]
> ### Description
> 
> Added a python file.
> 
> This is a solution to the problem of the nearest exit in a Maze. I have solved it using two different approaches, one using sets and one using DP. I've also attached the link to the problem (LeetCode).

Code looks good, do you want to add this task as a new Python - Medium issue to this repository or just to get this pull request merged?

**Comment by nik-6174** [comment]
I actually am very new to Github, and have not contributed in Open Source much, I'm trying to learn and understand how things work here, so I thought I would share some of my solutions here while figuring things out.
I'd appreciate if you merge this one, I'll try to follow what you said about creating unique tasks from the next time.

**Comment by nikohoffren** [comment]
> I actually am very new to Github, and have not contributed in Open Source much, I'm trying to learn and understand how things work here, so I thought I would share some of my solutions here while figuring things out.
> I'd appreciate if you merge this one, I'll try to follow what you said about creating unique tasks from the next time.

Sure! In the future, if you like you can either create new tasks for this project or solve some of the existing tasks that are are found in the Issues section.

**Comment by nikohoffren** [comment]
## Merged

> This is an automated message from Fork, Commit, Merge [BOT].

Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

### What's next?

If you're looking for more ways to contribute, I invite you to check out my other projects. Just click [here](https://github.com/nikohoffren?tab=repositories) to find more. These projects contain real issues that you can help resolve. You can also check out the [Influences](https://github.com/nikohoffren/fork-commit-merge#influences) section in the README to find more projects similar to this one.

Also please leave a star to this project if you feel it helped you, i would really appreciate it.

I look forward to seeing your contributions!

**Pull request merged**
