### PR TITLE
Update Frequency.java

### PR DESCRIPTION
**Pull request by FarukhS52**

### CODE REVIEW

**Review by nikohoffren — APPROVED** [review]
Code looks good! This doesn't actually use the HashMap that was requested in the description but your solution works too so it's fine.

**Comment by nikohoffren** [comment]
> ### Description
> ### Additional Context

Don't close your pull requests, otherwise they cannot be merged.

**Comment by FarukhS52** [comment]
I closed the pull request because it was not the required answer

**Comment by nikohoffren** [comment]
> I closed the pull request because it was not the required answer

Okay, i was going to merge it anyways since it works but that's fine.

**Comment by nikohoffren** [comment]
> > I closed the pull request because it was not the required answer
> 
> Okay, i was going to merge it anyways since it works but that's fine.

Also, there is no need to close PR:s, you can just simply make a new commit to the same branch and it updates here if you want to make some changes to the code.

**Comment by FarukhS52** [comment]
yeahh, i'll remember that for next time

**Pull request closed without merging**
