### PR TITLE
Fix issue - Easy Issue (TypeScript) #882

### PR DESCRIPTION
**Pull request by MaEdAlpha**
Added return statement for tasks/typescript/easy/index.ts

### CODE REVIEW

**Comment by MaEdAlpha** [comment]
Any PERN/MERN  open source projects you're looking for help contributing to?

**Review by nikohoffren — APPROVED** [review]
Return statement looks good!

**Comment by nikohoffren** [comment]
> Any PERN/MERN open source projects you're looking for help contributing to?

Not exactly MERN, but do have this NextJS, TypeScript, Tailwind, MongoDB repo, that is the website for this Fork Commit Merge project: [Fork, Commit, Merge - web](https://github.com/nikohoffren/fork-commit-merge-web).
There is only one issue open at the moment but feel free to make Issue or PR for something that you are interested changing or adding to the website if you like.

**Comment by nikohoffren** [comment]
## Merged

> This is an automated message from Fork, Commit, Merge [BOT].

Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

### What's next?

If you're looking for more ways to contribute, I invite you to check out my other projects. Just click [here](https://github.com/nikohoffren?tab=repositories) to find more. These projects contain real issues that you can help resolve. You can also check out the [Influences](https://github.com/nikohoffren/fork-commit-merge#influences) section in the README to find more projects similar to this one.

Also please leave a star to this project if you feel it helped you, i would really appreciate it.

I look forward to seeing your contributions!

**Comment by nikohoffren** [comment]
> > > Any PERN/MERN open source projects you're looking for help contributing to?
> > 
> > Not exactly MERN, but do have this NextJS, TypeScript, Tailwind, MongoDB repo, that is the website for this Fork Commit Merge project: [Fork, Commit, Merge - web](https://github.com/nikohoffren/fork-commit-merge-web). There is only one issue open at the moment but feel free to make Issue or PR for something that you are interested changing or adding to the website if you like.
> 
> Great! Will take a look and see if anything catches my fancy. Thanks again Niko! Enjoy the rest of your week.

No problem, happy to help. You too, have a good one!

**Pull request merged**
