### PR TITLE
Added required code in  index.html

### PR DESCRIPTION
**Pull request by sudhanshu-77**
Hey 👋 please check my PR, If need to change please inform , Please try to merge Fast. Thanks
solved issue #1164
I have Added code for clock hands using div elements with appropriate class names and data attributes.
and  Added code for clock numbers (1 to 12) using div elements with appropriate class names.

### CODE REVIEW

**Review by nikohoffren — CHANGES_REQUESTED** [review]
Hi!

The HTML looks good but `index.js` and `style.css` files are missing. If you look the issue description, this clock needs to be also functional.

**Comment by sudhanshu-77** [comment]
> Hi!
> 
> The HTML looks good but `index.js` and `style.css` files are missing. If you look the issue description, this clock needs to be also functional.

Please check I have also added Css and Js File. Please merge I am trying to do as much I can. Thanks

**Review by nikohoffren — CHANGES_REQUESTED** [review]
Thanks for providing the files but the clock seems not to be working. I suggest always testing the code locally before making any commits to see if it works.

Remember that this is Hard level issue, you can also try easy or medium issues if you like. This repository has 120 different issues with different languages/frameworks and varying difficulty.

**Comment by sudhanshu-77** [comment]
> Thanks for providing the files but the clock seems not to be working. I suggest always testing the code locally before making any commits to see if it works.
> 
> Remember that this is Hard level issue, you can also try easy or medium issues if you like. This repository has 120 different issues with several languages/frameworks and varying difficulty.

ok, thankyou for suggestions.

**Comment by nikohoffren** [comment]
> > Thanks for providing the files but the clock seems not to be working. I suggest always testing the code locally before making any commits to see if it works.
> > Remember that this is Hard level issue, you can also try easy or medium issues if you like. This repository has 120 different issues with several languages/frameworks and varying difficulty.
> 
> ok, thankyou for suggestions.

Are you still going to solve this pull request, or should i close it?

**Comment by sudhanshu-77** [comment]
You can close for now, I will work on  this issue later. Thank you

**Comment by sudhanshu-77** [comment]
> > > Thanks for providing the files but the clock seems not to be working. I suggest always testing the code locally before making any commits to see if it works.
> > > Remember that this is Hard level issue, you can also try easy or medium issues if you like. This repository has 120 different issues with several languages/frameworks and varying difficulty.
> > 
> > 
> > ok, thankyou for suggestions.
> 
> Are you still going to solve this pull request, or should i close it?

You can close for now, I will work on  this issue later. Thank you

**Comment by nikohoffren** [comment]
> > > > Thanks for providing the files but the clock seems not to be working. I suggest always testing the code locally before making any commits to see if it works.
> > > > Remember that this is Hard level issue, you can also try easy or medium issues if you like. This repository has 120 different issues with several languages/frameworks and varying difficulty.
> > > 
> > > 
> > > ok, thankyou for suggestions.
> > 
> > 
> > Are you still going to solve this pull request, or should i close it?
> 
> You can close for now, I will work on this issue later. Thank you

Okay, no problem!

**Comment by sudhanshu-77** [comment]
Hey 👋 please check my PR, If need to change please inform . Thanks
solved issue #1058
I have added the required form creation code in index.html , I have also checked Code is responsive . Please Review it.

**Pull request closed without merging**
