### PR TITLE
contributor

### PR DESCRIPTION
**Pull request by rickon43**
This are the changes which I want to add in the js file if there any suggestions is there to let me know

### CODE REVIEW

**Comment by nikohoffren** [comment]
> This are the changes which I want to add in the js file if there any suggestions is there to let me know

Hi! Which task is this referencing to? I don't see any files changed in the tasks directory.

**Comment by rickon43** [comment]
check in the commits just now added in commit tasks

**Comment by nikohoffren** [comment]
> check in the commits just now added in commit tasks

You committed three empty files within the new commit. Was the first commit about some kind of new issue suggestion?

**Review by nikohoffren — CHANGES_REQUESTED** [review]
You committed three empty files. Was the first commit about some kind of new issue suggestion for this project?

**Comment by rickon43** [comment]
yes, i suggested

**Comment by nikohoffren** [comment]
> yes, i suggested

Okay, so can you provide me name and description of the task you are suggesting, difficulty level (easy, medium, hard), installing instructions (if there are any) etc?

**Comment by nikohoffren** [comment]
Pull request closed because there was no answer from the pull request creator.

**Pull request closed without merging**
