### PR TITLE
Fixed issue Easy Issue (Markdown) #75

### PR DESCRIPTION
**Pull request by FrankXenarthra**
Added one empty line and surrounded url by angle brackets.

### CODE REVIEW

**Review by nikohoffren — CHANGES_REQUESTED** [review]
The angle brackets don't work in Markdown links, the link will work if you just get rid of the extra space like this: Visit our website '[here](https://forkcommitmerge.vercel.app)'

**Comment by nikohoffren** [comment]
> The angle brackets don't work in Markdown links, the link will work if you just get rid of the extra space like this: Visit our website [here](https://forkcommitmerge.vercel.app)

**Comment by FrankXenarthra** [comment]
@nikohoffren  Thank you for the help! I used mdl to check and https://github.com/updownpress/markdown-lint/blob/master/rules/034-no-bare-urls.md and this recommended the angles. I commited the New changes via the web editor now.

**Review by nikohoffren — APPROVED** [review]
Looks good!

**Comment by nikohoffren** [comment]
## Merged

> This is an automated message from Fork, Commit, Merge [BOT].

Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

### What's next?

If you're looking for more ways to contribute, I invite you to check out my other projects. Just click [here](https://github.com/nikohoffren?tab=repositories) to find more. These projects contain real issues that you can help resolve.

Also please leave a star to this project if you feel it helped you, i would really appreciate it.

I look forward to seeing your contributions!

**Comment by nikohoffren** [comment]
> @nikohoffren  Thank you for the help! I used mdl to check and https://github.com/updownpress/markdown-lint/blob/master/rules/034-no-bare-urls.md and this recommended the angles. I commited the New changes via the web editor now.

Great, it works now!
Those brackets do work if there is no placeholder text, but this issue had 'here' word as placeholder so that is why there is no need for brackets.

**Pull request merged**
