### PR TITLE
made an html contact form | please accept my PR for hacktoberfest 23 |

### PR DESCRIPTION
**Pull request by tanay-nagde**
made an html contact form , having name email message and a submit button 
Screenshot 2023-10-02 091021

### CODE REVIEW

**Review by nikohoffren — APPROVED** [review]
Form looks good!

**Comment by nikohoffren** [comment]
## Merged

> This is an automated message from Fork, Commit, Merge [BOT].

Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

### What's next?

If you're looking for more ways to contribute, I invite you to check out my other projects. Just click [here](https://github.com/nikohoffren?tab=repositories) to find more. These projects contain real issues that you can help resolve. You can also check out the [Influences](https://github.com/nikohoffren/fork-commit-merge#influences) section in the README to find more projects similar to this one.

Also please leave a star to this project if you feel it helped you, i would really appreciate it.

I look forward to seeing your contributions!

**Comment by tanay-nagde** [comment]
@nikohoffren could you please add hacktoberfest accepted to this pr

**Comment by nikohoffren** [comment]
> @nikohoffren could you please add hacktoberfest accepted to this pr

Sorry, but according to Hacktoberfest organizers, the tasks in this repo will not count towards Hacktoberfest, since this repository is an educational repository, hence against the Hacktoberfest guidelines.

**Comment by tanay-nagde** [comment]
@nikohoffren didnt knew that ,no problem

**Pull request merged**
