### PR TITLE
Added methods to calculator to adjust main code

### PR DESCRIPTION
**Pull request by ClearlyHere**
### Description

Added methods add, subtract, multiply and divide in Calculator class with double signatures to handle both integers and floats.

### Additional Context

Now the main code functions appropriately

### CODE REVIEW

**Review by nikohoffren — APPROVED** [review]
Looks good!

**Comment by nikohoffren** [comment]
## Merged

> This is an automated message from Fork, Commit, Merge [BOT].

Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

### What's next?

If you're looking for more ways to contribute, I invite you to check out my other projects. Just click [here](https://github.com/nikohoffren?tab=repositories) to find more. These projects contain real issues that you can help resolve. You can also check out the [Influences](https://github.com/nikohoffren/fork-commit-merge#influences) section in the README to find more projects similar to this one.

Also please leave a star to this project if you feel it helped you, i would really appreciate it.

I look forward to seeing your contributions!

**Comment by ClearlyHere** [comment]
Thanks a lot! I'm getting interested into contributing to open source and this was a nice way of learning how to do so. I will keep trying to a few ones before getting into other open-source projects to make sure I do it well!

**Comment by nikohoffren** [comment]
> Thanks a lot! I'm getting interested into contributing to open source and this was a nice way of learning how to do so. I will keep trying to a few ones before getting into other open-source projects to make sure I do it well!

Great! I'm glad if this project can help developers getting into open source.

**Pull request merged**
