### PR TITLE
Changed the color of the h1 element to red

### PR DESCRIPTION
**Pull request by yashwanthvarma18**
Description
In this pull request, I've made a simple yet impactful change to the website's style:

Changed the color of the h1 element to red by applying the .red class.
This modification will give the h1 element a more eye-catching appearance and enhance its visibility on the page.

Additional Context
No additional context or screenshots are required for this straightforward change. The color change can be easily observed by reviewing the code changes in the CSS file.

### CODE REVIEW

**Review by nikohoffren — APPROVED** [review]
Looks good!

**Comment by nikohoffren** [comment]
## Merged

> This is an automated message from Fork, Commit, Merge [BOT].

Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

### What's next?

If you're looking for more ways to contribute, I invite you to check out my other projects. Just click [here](https://github.com/nikohoffren?tab=repositories) to find more. These projects contain real issues that you can help resolve. You can also check out the [Influences](https://github.com/nikohoffren/fork-commit-merge#influences) section in the README to find more projects similar to this one.

Also please leave a star to this project if you feel it helped you, i would really appreciate it.

I look forward to seeing your contributions!

**Comment by yashwanthvarma18** [comment]
hey @nikohoffren why is it not showing accepted  in hactoberfest website

**Comment by nikohoffren** [comment]
> hey @nikohoffren why is it not showing accepted  in hactoberfest website 

Hi, i don't know how their calculating works, i assume they have some kind of bot that searches the hacktoberfest-accepted labels around GitHub. It should appear after some time.

**Comment by yashwanthvarma18** [comment]
hi @nikohoffren why my PR got excluded from hacktoberfest 
what happened ?

**Comment by nikohoffren** [comment]
> hi @nikohoffren why my PR got excluded from hacktoberfest 
> what happened ?
> 

Unfortunately, according to Hacktoberfest organizers, this repository is an educational repository, hence against the hacktoberfest guidelines. Which does make sense since the commits for Hacktoberfest should be "real" and meaningful, and the tasks in this repo are just for educational purposes.

**Comment by yashwanthvarma18** [comment]
1)TITLE: RESPONSIVE FEATURES SECTION & +PAGE.SVELTE UPDATES
2)TITLE: MADE 'OUR TEAM' SECTION MORE RESPONSIVE
3)TITLE: UPDATED ALT TEXT FOR RELEVANT IMAGES
4)TITLE: FIX BROKEN LINKS, UPDATE NAVIGATION, AND ADD SMOOTH SCROLLING ANIMATION

do you think the PR and merged issues will get accepted or should i do more hard ones, is there any contribution that is not meaning ful

**Comment by yashwanthvarma18** [comment]
1)TITLE: RESPONSIVE FEATURES SECTION & +PAGE.SVELTE UPDATES
2)TITLE: MADE 'OUR TEAM' SECTION MORE RESPONSIVE
3)TITLE: UPDATED ALT TEXT FOR RELEVANT IMAGES
4)TITLE: FIX BROKEN LINKS, UPDATE NAVIGATION, AND ADD SMOOTH SCROLLING ANIMATION

do you think the PR and merged issues will get accepted or should i do more hard ones, is there any contribution that is not meaningful @nikohoffren

**Comment by nikohoffren** [comment]
> 1)TITLE: RESPONSIVE FEATURES SECTION & +PAGE.SVELTE UPDATES
> 2)TITLE: MADE 'OUR TEAM' SECTION MORE RESPONSIVE
> 3)TITLE: UPDATED ALT TEXT FOR RELEVANT IMAGES
> 4)TITLE: FIX BROKEN LINKS, UPDATE NAVIGATION, AND ADD SMOOTH SCROLLING ANIMATION
> 
> do you think the PR and merged issues will get accepted or should i do more hard ones, is there any contribution that is not meaningful @nikohoffren 

I think those would be good contributions but Hacktoberfest won't accept any PR:s from this repository so i recommend finding other repositories to contribute to. You can find lots of different issues from other repositories from goodfirstissues.com for example.

**Comment by yashwanthvarma18** [comment]
why it wont accept

**Comment by yashwanthvarma18** [comment]
thanks for intimating me but i found the repository from goodfirstissues.com only so i dont know can you please suggest some of the "real" project repositories such as actual websites some of them that would really help me

**Comment by nikohoffren** [comment]
That should be accepted for Hacktoberfest, since those are real issues for
the website. It is not an educational repository.

ma 2. lokak. 2023 klo 19.01 Yashwanth Varma ***@***.***)
kirjoitti:

**Comment by nikohoffren** [comment]
Unfortunately I don't really know too much about Google Summer of Code. And
since the summer is already over, I recommend thinking about participating
in GSoC sometime during next year. You can find information about the
project here: https://summerofcode.withgoogle.com/

ma 2. lokak. 2023 klo 19.41 Yashwanth Varma ***@***.***)
kirjoitti:

**Pull request merged**
