### PR TITLE
Forked and Committed for learning purpose, Please provide a feedback …

### PR DESCRIPTION
**Pull request by Bishalsingh153**
…to help me improve

## Pull Request Type

What kind of change does this PR introduce?

[X] Solved an issue/task
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:

## What is the current behavior?

Issue Number: [#1414 ]

### CODE REVIEW

**Comment by Bishalsingh153** [comment]
Hello Sir, just entering the world of open source and trying to learn as much as i can. I have solved the issue. Please provide feedback whether everything well or not during the process.

**Review by nikohoffren — APPROVED** [review]
Code looks good! There are couple formatting issues but they are not important. The contributing process went as it should.

**Comment by nikohoffren** [comment]
## Merged

> This is an automated message from Fork, Commit, Merge [BOT].

Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

### What's next?

If you're looking for more ways to contribute, I invite you to check out my other projects. Just click [here](https://github.com/nikohoffren?tab=repositories) to find more. These projects contain real issues that you can help resolve. You can also check out the [Influences](https://github.com/nikohoffren/fork-commit-merge#influences) section in the README to find more projects similar to this one.

Also please leave a star to this project if you feel it helped you, i would really appreciate it.

I look forward to seeing your contributions!

**Comment by Bishalsingh153** [comment]
> Code looks good! There are couple formatting issues but they are not important. The contributing process went as it should.

Thank your response and feedback sir ,it means a lot to me. I will try to learn more by contributing to the project.

**Comment by nikohoffren** [comment]
> > Code looks good! There are couple formatting issues but they are not important. The contributing process went as it should.
> 
> Thank your response and feedback sir ,it means a lot to me. I will try to learn more by contributing to the project.

Sounds good! Thanks for contributing to this project.

**Pull request merged**
