### PR TITLE
made a cpp program that converts temperature

### PR DESCRIPTION
**Pull request by tanay-nagde**
### Description

made a cpp program from scratch that converts temperature 
please accept my pr for hacktoberfest 23

### CODE REVIEW

**Review by nikohoffren — APPROVED** [review]
Code for converter looks good!

**Comment by nikohoffren** [comment]
## Merged

> This is an automated message from Fork, Commit, Merge [BOT].

Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

### What's next?

If you're looking for more ways to contribute, I invite you to check out my other projects. Just click [here](https://github.com/nikohoffren?tab=repositories) to find more. These projects contain real issues that you can help resolve. You can also check out the [Influences](https://github.com/nikohoffren/fork-commit-merge#influences) section in the README to find more projects similar to this one.

Also please leave a star to this project if you feel it helped you, i would really appreciate it.

I look forward to seeing your contributions!

**Comment by tanay-nagde** [comment]
@nikohoffren just got a gitgurdian bot message some kind of hardcoded  secret, it has been showing to a file which i havent push could you please tell me more about it or look into the stuff
thankyou

**Comment by nikohoffren** [comment]
> @nikohoffren just got a gitgurdian bot message some kind of hardcoded  secret, it has been showing to a file which i havent push could you please tell me more about it or look into the stuff
> thankyou 

Hi! That is a Django related issue. There is a Secret Key in our Django task, which in real life situations should never be exposed, however in this educational repo it is exposed and that's why the GitGuardian complains for it. It has nothing to do with this issue though, im not sure why the bot added the message for several pull requests, it is probably how it is supposed to work to warn people for exposing secrets so it adds it to every PR. You can ignore those messages.

**Pull request merged**
