### PR TITLE
Pull request for bubble sort in python

### PR DESCRIPTION
**Pull request by surajTade**
Implemented bubble sort in python

### CODE REVIEW

**Comment by nikohoffren** [comment]
> Implemented bubble sort in python

Hi! Looks like there is no files added to this commit. Can you add the file and make a new commit, so i can review it?

**Review by nikohoffren — CHANGES_REQUESTED** [review]
Nothing committed.

**Comment by bhaavvya** [comment]
I have a doubt , I have already forked this repo and solved 1 issue and now I want to solve this issue as well but I cannot make a new pull request. Actually I don't know that well Can u please guide me?

**I want to solve this issue. Please guide me**

**Comment by nikohoffren** [comment]
> I have a doubt , I have already forked this repo and solved 1 issue and now I want to solve this issue as well but I cannot make a new pull request. Actually I don't know that well Can u please guide me?
> 
> **I want to solve this issue. Please guide me**

You can just do it the same way as you did earlier but first you have to make sure you have the latest changes from my repository since i added this task just recently and your local copy may not necessary have that.

So in VS Code or whatever editor you are using, go in your cloned Fork Commit Merge repository and make sure you are in the main branch by running this command in Terminal:
```bash
git switch main
```

Then run this:
```bash
git remote add upstream https://github.com/nikohoffren/fork-commit-merge.git
```

That will add a reference to my repository so you can fetch the latest changes from that. Then pull the latest changes to your cloned repository:
```bash
git pull upstream main
```
After that you should have the updated repo and you can make a new branch:
```bash
git switch -c fix-issue
```

Then you can start solving the issues and make the pull request as before following these instructions: https://github.com/nikohoffren/fork-commit-merge#submitting-your-changes

**Pull request closed without merging**
