### PR TITLE
Fixed issue:Typescript easy

### PR DESCRIPTION
**Pull request by Davidthecode**
Added the necessary return statement to the greet function so that it returns a greeting message. The function returns a string in the format Hello, [name]! where [name] is the value of the input argument.

### CODE REVIEW

**Review by nikohoffren — CHANGES_REQUESTED** [review]
Looks like there is node_modules folder added to this commit, but there should be only the `tasks/typescript/easy/index.ts` file. Can you make new commit where is only that one file instead of 3530 files? I don't know why .gitignore did not ignore that node_modules directory, even though it should not add it with commits. 

You can add add only the file requested by command `git add tasks/typescript/easy/index.ts` and then making new commit as before.

**Comment by Ereakin** [comment]
Have you tried using `node_modules/` in your .gitignore?
Seems to be the fix according to https://stackoverflow.com/a/51991384

**Comment by nikohoffren** [comment]
> Have you tried using `node_modules/` in your .gitignore? Seems to be the fix according to https://stackoverflow.com/a/51991384

Thanks for the tip! I think the issue is that since i am using Linux, and in Linux it can be just `node_modules` or `/node_modules` but maybe for Windows or Mac users it needs to be `node_modules/` then. I'll try it out.

**Comment by nikohoffren** [comment]
## Merged

> This is an automated message from Fork, Commit, Merge [BOT].

Thank you for your contribution! Your pull request has been merged. The files have been reset for the next contributor.

### What's next?

If you're looking for more ways to contribute, I invite you to check out my other projects. Just click [here](https://github.com/nikohoffren?tab=repositories) to find more. These projects contain real issues that you can help resolve.

Also please leave a star to this project if you feel it helped you, i would really appreciate it.

I look forward to seeing your contributions!

**Comment by Davidthecode** [comment]
okay @nikohoffren, done that

**Pull request merged**
