### PR TITLE
HTML Hard issue is fixed

### PR DESCRIPTION
**Pull request by Rajeevjewar**
Hi @nikohoffren, I fixed the HTML Hard issue. So please merge my changes to the main branch.

### CODE REVIEW

**Review by nikohoffren — APPROVED** [review]

**Comment by nikohoffren** [comment]
> Hi @nikohoffren, I fixed the HTML Hard issue. So please merge my changes to the main branch.

Code looks good!

**Comment by Rajeevjewar** [comment]
What exactly changes do I need to make?

**Comment by nikohoffren** [comment]
> What exactly changes do I need to make?

I'm not sure since i cannot see them myself. You can click the Resolve conflicts button and maybe share a screenshot to me and i can help if there are some problems.

**Comment by Rajeevjewar** [comment]
Actually these  **.DS_Store file**  **tasks/.DS_Store** **tasks/html/.DS_Store** files are added extra somehow or by mistake. So can you please tell me how I can delete them and raise the pull request again?

Screenshot 2023-08-31 at 11 27 39 PM

Screenshot 2023-08-31 at 11 31 46 PM

**Review by Rajeevjewar — COMMENTED** [review]
These .DS_Store unknown files are added by mistake. So please tell me how can I delete them.

**Comment by nikohoffren** [comment]
> Actually these **.DS_Store file** **tasks/.DS_Store** **tasks/html/.DS_Store** files are added extra somehow or by mistake. So can you please tell me how I can delete them and raise the pull request again?
> Screenshot 2023-08-31 at 11 27 39 PM Screenshot 2023-08-31 at 11 31 46 PM

You could create a new branch from the main just like before and then delete the DS_Store files in your editor if they are still there for some reason. Then make a new commit and new pull request. Remember to copy your solution for this issue so you don't have to do that again. Of course you can always switch back to this current fix-issue-hard branch if you need to see them.

**Pull request closed without merging**
